In [ ]:
"""
feature binning:
  unsupervised:
    equals-width
    equals-count
  supervised:
    entrophy
"""

In [1]:
import pandas as pd
import numpy as np

# Create a static dataset
data = np.array([10, 12, 15, 18, 20, 22, 25, 30, 35, 40, 42, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100])
df = pd.DataFrame({'Value': data}) # Create a DataFrame with a 'Value' column

print("Original DataFrame:")
display(df.head())

Original DataFrame:

   Value
0     10
1     12
2     15
3     18
4     20

In [ ]:
# Define the number of bins
num_bins_width = 5

# Perform equal-width binning using pd.cut on the DataFrame column
df['Equal_Width_Bins'] = pd.cut(df['Value'], bins=num_bins_width)

print(f"Equal-Width Binning (into {num_bins_width} bins):\n")
display(df['Equal_Width_Bins'].value_counts().sort_index())
print("\nBin labels for each data point (first 5 rows):")
display(df[['Value', 'Equal_Width_Bins']].head())

Equal-Width Binning (into 5 bins):

Equal_Width_Bins
(9.91, 28.0]     7
(28.0, 46.0]     5
(46.0, 64.0]     3
(64.0, 82.0]     4
(82.0, 100.0]    4
Name: count, dtype: int64

Bin labels for each data point (first 5 rows):

   Value Equal_Width_Bins
0     10     (9.91, 28.0]
1     12     (9.91, 28.0]
2     15     (9.91, 28.0]
3     18     (9.91, 28.0]
4     20     (9.91, 28.0]

### 2. Equal-Count Binning (equals-count)

Equal-count binning (also known as quantile binning) divides the data into `n` bins such that each bin contains approximately the same number of observations. The bin boundaries are determined by the quantiles of the data.

In [ ]:
# Define the number of bins
num_bins_count = 5

# Perform equal-count binning using pd.qcut on the DataFrame column
df['Equal_Count_Bins'] = pd.qcut(df['Value'], q=num_bins_count, duplicates='drop') # 'duplicates' handles cases with identical values at quantile boundaries

print(f"Equal-Count Binning (into {num_bins_count} bins):\n")
display(df['Equal_Count_Bins'].value_counts().sort_index())
print("\nBin labels for each data point (first 5 rows):")
display(df[['Value', 'Equal_Count_Bins']].head())

Equal-Count Binning (into 5 bins):

Equal_Count_Bins
(9.999, 20.8]    5
(20.8, 39.0]     4
(39.0, 56.0]     5
(56.0, 78.0]     4
(78.0, 100.0]    5
Name: count, dtype: int64

Bin labels for each data point (first 5 rows):

   Value Equal_Count_Bins
0     10    (9.999, 20.8]
1     12    (9.999, 20.8]
2     15    (9.999, 20.8]
3     18    (9.999, 20.8]
4     20    (9.999, 20.8]